#Snakemake configuration file

# Specify paths to data files for each snakemake run

# Paths must end with forward slash

#project directory
dir_proj: /project2/gilad/briana/Total_Nuc_RNA_seq_data/170428_K00242_0214_AHK2GMBBXX-YG-SP20/

#ref genome directory
dir_genome: /project2/gilad/briana/genome_anotation_data/

#files for picard:
ref_flat: /project2/gilad/briana/genome_anotation_data/gencode.v19.annotation2.nochr.refFlat
ribosome_intervals: /project2/gilad/briana/genome_anotation_data/hg19.rRNA.intervals

#files for protien coding gene coverage (created for https://brimittleman.github.io/Net-seq/strand_spec.html)  
genes_bed: /project2/gilad/briana/genome_anotation_data/gencode.v19.annotation.proteincodinggene.sort.bed

#directory with aditional scripts:
scripts: /project2/gilad/briana/threeprimeseq/code/

# Make sure to also update path for log files in cluster.json
dir_log: log/

# Specify Ensembl release for genome sequence and annotation
# http://feb2014.archive.ensembl.org/index.html
ensembl_archive: feb2014.archive.ensembl.org
ensembl_rel: 75
ensembl_genome: GRCh37.75


#Specify chromosomes
#
# For quantifying gene expression
chr_genes: ["1", "2", "3", "4", "5", "6", "7", "8", "9",
            "10", "11", "12", "13", "14", "15", "16",
            "17", "18", "19", "20", "21", "22",
            "X", "Y", "MT"]
